default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ToDoApp_development
  username: mytodoapp
  password: p@ssw0rd

 
# test:
#   <<: *default
#   database: ToDoApp_test


# production:
#   <<: *default
#   database: ToDoApp_production
#   username: ToDoApp
#   password: <%= ENV['TODOAPP_DATABASE_PASSWORD'] %>
